spring:
  cloud:
    gateway:
      routes:
        - id: test_gateway
          uri: https://www.baidu.com
          predicates:
            - Query=uri,baidu

        - id: product_rout
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_rout
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
